---
apiVersion: v1
kind: Service
metadata:
  name: moon
  namespace: {{ .Release.Namespace }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
{{- with .Values.service.externalIPs }}
  externalIPs:
  {{- range . }}
  - {{ . }}
  {{- end }}
{{- end }}
  selector:
    app: moon
  ports:
  - name: "moon"
    protocol: TCP
    port: {{ .Values.moon.port }}
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: moon-ui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: moon
  ports:
  - name: "moon-ui"
    protocol: TCP
    port: {{ .Values.moonUI.port }}
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: browsers
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    moon: browser
  clusterIP: None
  publishNotReadyAddresses: true
#  ports: # Uncomment the following lines if you have Kubernetes < 1.13
#    - name: wd
#      port: 4444
#      protocol: TCP
#      targetPort: 4444
#    - name: vnc
#      port: 5900
#      protocol: TCP
#      targetPort: 5900

